<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="SSTR0038" name="com.ajmal.testcases.ReportsTest" tests="4" failures="0" timestamp="12 Oct 2018 18:31:36 GMT" time="21.435" errors="1">
  <testcase name="createReportTemplateTest" time="21.433" classname="com.ajmal.testcases.ReportsTest"/>
  <testcase name="editReportTemplateTest" time="0.002" classname="com.ajmal.testcases.ReportsTest">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	Duplicate local variable logout
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	Duplicate local variable logout

	at com.ajmal.testcases.ReportsTest.editReportTemplateTest(ReportsTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- editReportTemplateTest -->
  <testcase name="copyReportTemplateTest" time="0.000" classname="com.ajmal.testcases.ReportsTest">
    <skipped/>
  </testcase> <!-- copyReportTemplateTest -->
  <testcase name="deleteReportTemplateTest" time="0.000" classname="com.ajmal.testcases.ReportsTest">
    <skipped/>
  </testcase> <!-- deleteReportTemplateTest -->
</testsuite> <!-- com.ajmal.testcases.ReportsTest -->
